# Generated by Django 4.0.5 on 2022-06-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.CharField(max_length=255, verbose_name='Цена'),
        ),
    ]
