# Generated by Django 4.0.5 on 2022-06-20 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0002_alter_price_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cat_gallery', to='locks.category', verbose_name='Категория'),
        ),
    ]
