# Generated by Django 4.0.5 on 2022-06-20 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0003_alter_gallery_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locks.category', verbose_name='Категория'),
        ),
    ]
